const express = require('express')
const router = express.Router()
const { register, verifyEmail, login, forgotPassword, getResetPassword, resetPassword, getAllUsers } = require('../controllers/userRouters')
router.get('/users', getAllUsers)
router.post('/register', register)
router.post('/verify-email', verifyEmail)
router.post('/login', login)
router.post('/forgot-password', forgotPassword)
// router.get('/reset-password', getResetPassword)
router.post('/reset-password', resetPassword)
module.exports = router